deployment:
  tasks:
    - export DEPLOYPATH=/home/repositories/cybernetic
    - cp index.html $DEPLOYPATH
    - cp style.css $DEPLOYPATH
    - cp script.js $DEPLOYPATH
    - cp -R images $DEPLOYPATH/images 